### ISSUE TITLE
Any way to do pixelated shadows?

### ISSUE THREAD

**Issue by StarrKiss** [tanema/light_world.lua#45]
https://www.youtube.com/watch?v=sIiSpLL-sAg
This video is the sort of results I am hoping for, however, the lighting library that they use is hopelessly outdated - I tried updating it/fixing it for a solid 30 minutes and barely got any results. I would like to achieve similar results with this more modern lighting system, but I have NO IDEA how to achieve such pixellated light as in the original.

**Comment by tanema** [comment]
I would either suggest a shader to pixelate the lighting drawing with this library or I attached an updated version of the one you want. I modernized it and used a regular camera library that everyone uses instead of a manual canvas so that you could understand it better. 

[pixelshade.zip](https://github.com/tanema/light_world.lua/files/7476090/pixelshade.zip)
